apiVersion: apps/v1

# k8s deployment object
kind: Deployment
metadata:
  name: grafana-deployment
  # labels for future selection
  labels:
    app  : grafana
    owner: aherlind
spec:
  # pods updating strategy
  strategy:
    # type RollingUpdate updates pods smoothly
    type: RollingUpdate
    rollingUpdate:
      # maximum count of unavailable pods
      maxUnavailable: 1
      # over the desired amount of pods
      maxSurge: 1
  # select pods
  selector:
    # choose with labels
    matchLabels:
      app: grafana
  # pods creating template
  template:
    metadata:
      # labels for future selection
      labels:
        app: grafana
    # configs for containers
    spec:
      containers:
      - name: grafana
        # docker image for container
        image: grafana
        # turn off pulling on DockerHub
        imagePullPolicy: Never
        # open ports in container
        ports:
        - containerPort: 3000

---

apiVersion: v1

# k8s deployment object
kind: Service
metadata:
  # service name
  name: grafana-service
  # gives the right to use one ip
  annotations:
    metallb.universe.tf/allow-shared-ip: services
  # labels for future selection
  labels:
      app  : grafana
      owner: aherlind
spec:
  # service type is LoadBalancer
  type: LoadBalancer
  # select pods
  selector:
    app: grafana
  ports:
  - name: http
    # redirect incoming request from port
    port: 3000
    # send incoming request to container with port
    targetPort: 3000
