apiVersion : apps/v1

# k8s deployment object
kind       : Deployment
metadata   :
  name  : nginx-deployment
  # labels for future selection
  labels:
    app   : nginx
    owner : aherlind
spec:
  # select pods
  selector :
    # choose with labels
    matchLabels:
      app: nginx
  # pods template for creating
  template:
    metadata:
      # labels for future selection
      labels:
        app     : nginx
        owner   : aherlind
    # configs for containers
    spec:
      containers:
        - name            : nginx
          # docker image for container
          image           : nginx
          # turn off pulling on DockerHub
          imagePullPolicy : Never
          # open ports in container
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 22

---

apiVersion: v1

# k8s service object
kind: Service
metadata:
  # service name
  name  : nginx-service
  # gives the right to use one ip
  annotations:
    metallb.universe.tf/allow-shared-ip: services
  # labels for future selection
  labels:
    app: nginx
    owner : aherlind
spec:
  # service type is LoadBalancer
  type    : LoadBalancer
  # select pods
  selector:
    app: nginx
  ports:
    - name      : http
      protocol  : TCP
      # redirect incoming request from port
      port      : 80
      # send incoming request to container with port
      targetPort: 80
    - name      : https
      protocol  : TCP
      # redirect incoming request from port
      port      : 443
      # send incoming request to container with port
      targetPort: 443
    - name      : ssh
      # redirect incoming request from port
      port      : 22
      # send incoming request to container with port
      targetPort: 22
