apiVersion: apps/v1

# k8s deployment object
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  # labels for future selection
  labels:
    app  : phpmyadmin
    owner: aherlind
spec:
  # select pods
  selector:
    # choose with labels
    matchLabels:
      app: phpmyadmin
  # pods template for creating
  template:
    metadata:
      # labels for future selection
      labels:
        app: phpmyadmin
        owner: aherlind
    # configs for containers
    spec:
      containers:
        - name           : phpmyadmin
          # docker image for container
          image          : phpmyadmin
          # turn off pulling on DockerHub
          imagePullPolicy: Never
          # open ports in container
          ports:
            - containerPort: 5000

---

apiVersion: v1

# k8s deployment object
kind: Service
metadata:
  # service name
  name: phmyadmin-service
  # gives the right to use one ip
  annotations:
    metallb.universe.tf/allow-shared-ip: services
  # labels for future selection
  labels:
    app  : phpmyadmin
    owner: aherlind
spec:
  # service type is LoadBalancer
  type: LoadBalancer
  # select pods
  selector:
    # choose with labels
    app: phpmyadmin
  ports:
    - name      : http
      # redirect incoming request from port
      port      : 5000
      # send incoming request to container with port
      targetPort: 5000
