apiVersion: apps/v1

# k8s deployment object
kind      : Deployment
metadata:
  name: wordpress-deployment
  # labels for future selection
  labels:
    app  : wordpress
    owner: aherlind
spec:
  # select pods
  selector:
    # choose with labels
    matchLabels:
      app: wordpress
  # pods template for creating
  template:
    metadata:
      labels:
        app: wordpress
    # configs for containers
    spec:
      containers:
      - name           : wordpress
        # docker image for container
        image          : wordpress
        # turn off pulling on DockerHub
        imagePullPolicy: Never
        # open ports in container
        ports:
        - containerPort: 5050

---

apiVersion: v1

# k8s deployment object
kind: Service
metadata:
  # service name
  name: wordpress-service
  # gives the right to use one ip
  annotations:
    metallb.universe.tf/allow-shared-ip: services
  # labels for future selection
  labels:
      app  : wordpress
      owner: aherlind
spec:
  # service type is LoadBalancer
  type: LoadBalancer
  # select pods
  selector:
    # choose with labels
    app: wordpress
  ports:
    - name      : http
      protocol  : TCP
      # redirect incoming request from port
      port      : 5050
      # send incoming request to container with port
      targetPort: 5050
