apiVersion: apps/v1

# k8s deployment object
kind: Deployment
metadata:
    name: ftps-deployment
    # labels for future selection
    labels:
        app   : ftps
        owner : aherlind
spec:
    # pods updating strategy
    strategy:
        # type RollingUpdate updates pods smoothly
        type: RollingUpdate
        rollingUpdate:
            # maximum count of unavailable pods
            maxUnavailable: 1
            # over the desired amount of pods
            maxSurge: 1
    # select pods
    selector:
        # choose with labels
        matchLabels:
            app: ftps
    # pods creating template
    template:
        metadata:
            # labels for future selection
            labels:
                app: ftps
                owner   : aherlind
        # configs for containers
        spec:
            containers:
                - name: ftps
                  # docker image for container
                  image: ftps
                  # turn off pulling on DockerHub
                  imagePullPolicy: Never
                  # open ports in container
                  ports:
                      - containerPort: 21
                      - containerPort: 21000

---

apiVersion: v1

# k8s deployment object
kind: Service
metadata:
    # service name
    name: ftps-service
    # gives the right to use one ip
    annotations:
        metallb.universe.tf/allow-shared-ip: services
    # labels for future selection
    labels:
        app: ftps
        owner : aherlind
spec:
    # service type is LoadBalancer
    type: LoadBalancer
    # select pods
    selector:
        app: ftps
    ports:
        - name: ftps
          # redirect incoming request from port
          port: 21
          # send incoming request to container with port
          targetPort: 21
        - name: ftps-pasv
          # redirect incoming request from port
          port: 21000
          # send incoming request to container with port
          targetPort: 21000
